#!/usr/bin/python3

import sys, os
from datetime import datetime
import base64
import hashlib

args = sys.argv

if len(args) < 2:
    print("Supply an argument for log string!")
    sys.exit(1)
elif len(args) > 2:
    print("Too many arguments!")
    sys.exit(1)

log_string = args[1]

try:
    log = open("log.txt")
    log.close()

    try: 
        if os.path.getsize("log.txt") != 0 and os.path.getsize("loghead.txt") != 0: # both not empty, write new log str according to head pointer
            loghead = open("loghead.txt", "r")
            hash_head_pointer = loghead.readline()
            hash_head_pointer = hash_head_pointer.strip()
            date_time = str(datetime.now())
            new_log = "".join(list(date_time)[:19]) + " - " + hash_head_pointer + " " + log_string.replace("\n", " ")
            loghead.close()
            
            loghead = open("loghead.txt", "w")
            hash_str = hashlib.sha256(new_log.encode("ascii")).hexdigest()
            base64_str = base64.b64encode(hash_str.encode("ascii")).decode("ascii")
            loghead.write(base64_str)
            loghead.close()

            log = open("log.txt", "a")
            log.write(new_log + "\n")
            log.close()
        elif os.path.getsize("log.txt") == 0 and os.path.getsize("loghead.txt") != 0: # only log empty, write log str with "begin" and override loghead head pointer
            date_time = str(datetime.now())
            new_log = "".join(list(date_time)[:19]) + " - " + "begin" + " " + log_string.replace('\n', ' ')

            loghead = open("loghead.txt", "w")
            hash_str = hashlib.sha256(new_log.encode("ascii")).hexdigest()
            base64_str = base64.b64encode(hash_str.encode("ascii")).decode("ascii")
            loghead.write(base64_str)
            loghead.close()

            log = open("log.txt", "a")
            log.write(new_log + "\n")
            log.close()
        elif os.path.getsize("loghead.txt") == 0 and os.path.getsize("log.txt") != 0: # only loghead empty, error message empty file
            print("loghead.txt is empty!")
            sys.exit(1)
        else: # both log and loghead are empty, write new log str according to head pointer
            date_time = str(datetime.now())
            new_log = "".join(list(date_time)[:19]) + " - " + "begin" + " " + log_string.replace('\n', ' ')

            loghead = open("loghead.txt", "w")
            hash_str = hashlib.sha256(new_log.encode("ascii")).hexdigest()
            base64_str = base64.b64encode(hash_str.encode("ascii")).decode("ascii")
            loghead.write(base64_str)
            loghead.close()

            log = open("log.txt", "a")
            log.write(new_log + "\n")
            log.close()
            

    except FileNotFoundError: # only log.txt exist
        print("loghead.txt is missing!")
        sys.exit(1)

except FileNotFoundError:
    # only loghead.txt exist: create log with "begin" and override loghead head pointer
    # neither log.txt and loghead.txt exist: create both and with "begin"

    date_time = str(datetime.now())
    new_log = "".join(list(date_time)[:19]) + " - " + "begin" + " " + log_string.replace('\n', ' ')

    loghead = open("loghead.txt", "w")
    hash_str = hashlib.sha256(new_log.encode("ascii")).hexdigest()
    base64_str = base64.b64encode(hash_str.encode("ascii")).decode("ascii")
    loghead.write(base64_str)
    loghead.close()

    log = open("log.txt", "w")
    log.write(new_log + "\n")
    log.close()
